-- ============================================================================
-- Olimpiadas Scouts · Datos iniciales
-- ============================================================================
-- Idempotente: puede ejecutarse varias veces sin duplicar información.
-- No crea usuarios; el administrador se crea con `npm run seed:admin`.
-- ============================================================================

-- ─── Configuración del evento ────────────────────────────────────────────────
insert into public.settings (id) values (true) on conflict (id) do nothing;

-- ─── Ramas scouts ────────────────────────────────────────────────────────────
insert into public.branches (id, name, sort_order) values
  ('manada',     'Manada',     1),
  ('tropa',      'Tropa',      2),
  ('caminantes', 'Caminantes', 3),
  ('rovers',     'Rovers',     4)
on conflict (id) do nothing;

-- ─── Países ──────────────────────────────────────────────────────────────────
insert into public.countries (code, name) values
  ('AF', 'Afganistán'),
  ('AL', 'Albania'),
  ('DE', 'Alemania'),
  ('AD', 'Andorra'),
  ('AO', 'Angola'),
  ('AG', 'Antigua y Barbuda'),
  ('SA', 'Arabia Saudita'),
  ('DZ', 'Argelia'),
  ('AR', 'Argentina'),
  ('AM', 'Armenia'),
  ('AU', 'Australia'),
  ('AT', 'Austria'),
  ('AZ', 'Azerbaiyán'),
  ('BS', 'Bahamas'),
  ('BD', 'Bangladés'),
  ('BB', 'Barbados'),
  ('BH', 'Baréin'),
  ('BE', 'Bélgica'),
  ('BZ', 'Belice'),
  ('BJ', 'Benín'),
  ('BY', 'Bielorrusia'),
  ('MM', 'Birmania (Myanmar)'),
  ('BO', 'Bolivia'),
  ('BA', 'Bosnia y Herzegovina'),
  ('BW', 'Botsuana'),
  ('BR', 'Brasil'),
  ('BN', 'Brunéi'),
  ('BG', 'Bulgaria'),
  ('BF', 'Burkina Faso'),
  ('BI', 'Burundi'),
  ('BT', 'Bután'),
  ('CV', 'Cabo Verde'),
  ('KH', 'Camboya'),
  ('CM', 'Camerún'),
  ('CA', 'Canadá'),
  ('QA', 'Catar'),
  ('TD', 'Chad'),
  ('CL', 'Chile'),
  ('CN', 'China'),
  ('CY', 'Chipre'),
  ('CO', 'Colombia'),
  ('KM', 'Comoras'),
  ('KP', 'Corea del Norte'),
  ('KR', 'Corea del Sur'),
  ('CI', 'Costa de Marfil'),
  ('CR', 'Costa Rica'),
  ('HR', 'Croacia'),
  ('CU', 'Cuba'),
  ('DK', 'Dinamarca'),
  ('DM', 'Dominica'),
  ('EC', 'Ecuador'),
  ('EG', 'Egipto'),
  ('SV', 'El Salvador'),
  ('AE', 'Emiratos Árabes Unidos'),
  ('ER', 'Eritrea'),
  ('SK', 'Eslovaquia'),
  ('SI', 'Eslovenia'),
  ('ES', 'España'),
  ('US', 'Estados Unidos'),
  ('EE', 'Estonia'),
  ('SZ', 'Esuatini'),
  ('ET', 'Etiopía'),
  ('PH', 'Filipinas'),
  ('FI', 'Finlandia'),
  ('FJ', 'Fiyi'),
  ('FR', 'Francia'),
  ('GA', 'Gabón'),
  ('GM', 'Gambia'),
  ('GE', 'Georgia'),
  ('GH', 'Ghana'),
  ('GD', 'Granada'),
  ('GR', 'Grecia'),
  ('GT', 'Guatemala'),
  ('GN', 'Guinea'),
  ('GW', 'Guinea-Bisáu'),
  ('GQ', 'Guinea Ecuatorial'),
  ('GY', 'Guyana'),
  ('HT', 'Haití'),
  ('HN', 'Honduras'),
  ('HU', 'Hungría'),
  ('IN', 'India'),
  ('ID', 'Indonesia'),
  ('IQ', 'Irak'),
  ('IR', 'Irán'),
  ('IE', 'Irlanda'),
  ('IS', 'Islandia'),
  ('MH', 'Islas Marshall'),
  ('SB', 'Islas Salomón'),
  ('IL', 'Israel'),
  ('IT', 'Italia'),
  ('JM', 'Jamaica'),
  ('JP', 'Japón'),
  ('JO', 'Jordania'),
  ('KZ', 'Kazajistán'),
  ('KE', 'Kenia'),
  ('KG', 'Kirguistán'),
  ('KI', 'Kiribati'),
  ('KW', 'Kuwait'),
  ('LA', 'Laos'),
  ('LS', 'Lesoto'),
  ('LV', 'Letonia'),
  ('LB', 'Líbano'),
  ('LR', 'Liberia'),
  ('LY', 'Libia'),
  ('LI', 'Liechtenstein'),
  ('LT', 'Lituania'),
  ('LU', 'Luxemburgo'),
  ('MK', 'Macedonia del Norte'),
  ('MG', 'Madagascar'),
  ('MY', 'Malasia'),
  ('MW', 'Malaui'),
  ('MV', 'Maldivas'),
  ('ML', 'Malí'),
  ('MT', 'Malta'),
  ('MA', 'Marruecos'),
  ('MU', 'Mauricio'),
  ('MR', 'Mauritania'),
  ('MX', 'México'),
  ('FM', 'Micronesia'),
  ('MD', 'Moldavia'),
  ('MC', 'Mónaco'),
  ('MN', 'Mongolia'),
  ('ME', 'Montenegro'),
  ('MZ', 'Mozambique'),
  ('NA', 'Namibia'),
  ('NR', 'Nauru'),
  ('NP', 'Nepal'),
  ('NI', 'Nicaragua'),
  ('NE', 'Níger'),
  ('NG', 'Nigeria'),
  ('NO', 'Noruega'),
  ('NZ', 'Nueva Zelanda'),
  ('OM', 'Omán'),
  ('NL', 'Países Bajos'),
  ('PK', 'Pakistán'),
  ('PW', 'Palaos'),
  ('PA', 'Panamá'),
  ('PG', 'Papúa Nueva Guinea'),
  ('PY', 'Paraguay'),
  ('PE', 'Perú'),
  ('PL', 'Polonia'),
  ('PT', 'Portugal'),
  ('GB', 'Reino Unido'),
  ('CF', 'República Centroafricana'),
  ('CZ', 'República Checa'),
  ('CG', 'República del Congo'),
  ('CD', 'República Democrática del Congo'),
  ('DO', 'República Dominicana'),
  ('RW', 'Ruanda'),
  ('RO', 'Rumania'),
  ('RU', 'Rusia'),
  ('WS', 'Samoa'),
  ('KN', 'San Cristóbal y Nieves'),
  ('SM', 'San Marino'),
  ('VC', 'San Vicente y las Granadinas'),
  ('LC', 'Santa Lucía'),
  ('VA', 'Ciudad del Vaticano'),
  ('ST', 'Santo Tomé y Príncipe'),
  ('SN', 'Senegal'),
  ('RS', 'Serbia'),
  ('SC', 'Seychelles'),
  ('SL', 'Sierra Leona'),
  ('SG', 'Singapur'),
  ('SY', 'Siria'),
  ('SO', 'Somalia'),
  ('LK', 'Sri Lanka'),
  ('ZA', 'Sudáfrica'),
  ('SD', 'Sudán'),
  ('SS', 'Sudán del Sur'),
  ('SE', 'Suecia'),
  ('CH', 'Suiza'),
  ('SR', 'Surinam'),
  ('TH', 'Tailandia'),
  ('TZ', 'Tanzania'),
  ('TJ', 'Tayikistán'),
  ('TL', 'Timor Oriental'),
  ('TG', 'Togo'),
  ('TO', 'Tonga'),
  ('TT', 'Trinidad y Tobago'),
  ('TN', 'Túnez'),
  ('TM', 'Turkmenistán'),
  ('TR', 'Turquía'),
  ('TV', 'Tuvalu'),
  ('UA', 'Ucrania'),
  ('UG', 'Uganda'),
  ('UY', 'Uruguay'),
  ('UZ', 'Uzbekistán'),
  ('VU', 'Vanuatu'),
  ('VE', 'Venezuela'),
  ('VN', 'Vietnam'),
  ('YE', 'Yemen'),
  ('DJ', 'Yibuti'),
  ('ZM', 'Zambia'),
  ('ZW', 'Zimbabue'),
  ('PS', 'Palestina')
on conflict (code) do nothing;

-- ─── Deportes ────────────────────────────────────────────────────────────────
-- Las tarifas quedan en NULL para que hereden las generales de `settings`.
-- Ojo: `group_team_fee` arranca en 0, tal como venía del prototipo. El
-- administrador debe fijarla en Configuración antes de cobrar equipos grupales.
insert into public.sports (
  slug, name, icon, type, description, category, team_size, substitutes,
  max_teams_per_group, max_sports_per_participant, deadline, fee,
  allow_intergroup, max_external, sort_order
) values
  ('futbol', 'Fútbol', '⚽', 'group',
   'Competencia por equipos en cancha reglamentaria.', 'Mixta',
   5, 2, 2, 3, '2026-12-01', null, true, 3, 1),
  ('carrera-relevos', 'Carrera de relevos', '🏃', 'group',
   'Prueba de velocidad y coordinación por postas.', 'Abierta',
   4, 1, 2, 3, '2026-12-01', null, true, 2, 2),
  ('voleibol', 'Voleibol', '🏐', 'group',
   'Competencia por equipos en cancha de arena.', 'Mixta',
   6, 2, 1, 2, '2026-12-01', null, true, 3, 3),
  ('atletismo-100m', 'Atletismo 100 m', '🏁', 'individual',
   'Prueba individual de velocidad.', 'Individual',
   1, 0, 1, 3, '2026-12-01', null, false, 0, 4),
  ('ajedrez', 'Ajedrez', '♟️', 'individual',
   'Competencia individual por sistema suizo.', 'Individual',
   1, 0, 1, 3, '2026-12-01', null, false, 0, 5)
on conflict (slug) do nothing;

-- ─── Ramas habilitadas por deporte ───────────────────────────────────────────
insert into public.sport_branches (sport_id, branch_id)
select s.id, b.branch_id
from public.sports s
join (values
  ('futbol',          'tropa'),
  ('futbol',          'caminantes'),
  ('futbol',          'rovers'),
  ('carrera-relevos', 'manada'),
  ('carrera-relevos', 'tropa'),
  ('carrera-relevos', 'caminantes'),
  ('carrera-relevos', 'rovers'),
  ('voleibol',        'caminantes'),
  ('voleibol',        'rovers'),
  ('atletismo-100m',  'tropa'),
  ('atletismo-100m',  'caminantes'),
  ('atletismo-100m',  'rovers'),
  ('ajedrez',         'manada'),
  ('ajedrez',         'tropa'),
  ('ajedrez',         'caminantes'),
  ('ajedrez',         'rovers')
) as b(sport_slug, branch_id) on b.sport_slug = s.slug
on conflict do nothing;
