/**
 * Grupos scout ya conocidos por la organización. El registro público solo
 * admite escoger uno de esta lista (ya no texto libre): antes la gente
 * escribía el nombre de cualquier forma y quedaban duplicados o variaciones
 * del mismo grupo. Única fuente de verdad, compartida entre el combobox del
 * formulario y la validación del servidor para que nunca queden desincronizados.
 */
export const KNOWN_GROUP_NAMES = [
  'G.S 1 PRIMERO',
  'G.S 2 UPB',
  'G.S 3 GUACIRÍ',
  'G.S 3 QUIMBAYAS',
  'G.S 4 IV SAN IGNACIO',
  'G.S 5 KENYA',
  'G.S 6 CÓNDORES',
  'G.S 7 ANSALON DE KRYNN',
  'G.S 8 CATIOS',
  'G.S 8 AMANZI',
  'G.S 9 YGGDRASILL',
  'G.S 10 MAFEKING',
  'G.S 21 TAHAMIES',
  'G.S 22 NASSAU',
  'G.S 23 PIJAOS',
  'G.S 24 MOSQUETEROS',
  'G.S 28 NUSEDECHI',
  'G.S 30 XXX DE TAR',
  'G.S 31 KAYSEEPAX',
  'G.S 32 TUDOR',
  'G.S 33 HELADE',
  'G.S 44 EL DORADO',
  'G.S 49 FRANCISCO ZAPATA',
  'G.S 50 QUIMBAYA',
  'G.S 52 ANACONAS',
  'G.S 53 SAN FRANCISCO',
  'G.S 59 LOS DELFINES',
  'G.S 60 CÓNDORES',
  'G.S 61 ARKHIA',
  'G.S 66 QUIRAMAS',
  'G.S 69 WAYRA',
  'G.S 71 RAKUT',
  'G.S 76 SAN AGUSTIN',
  'G.S 95 UBUNTU CALATRAVA',
  'G.S 100 DEFENSORES MEDELLIN',
  'G.S 103 WATHABU',
  'G.S 105 ARDA UPB',
  'G.S 107 GALILEO',
  'G.S 108 SATTWA',
  'G.S 109 CHAKANA',
  'G.S 111 INTISANA',
  'G.S 112 KIMYARIPANDA',
  'G.S 114 CELTA',
  'G.S 126 KHYMERA CALASANZ',
  'G.S 127 VIKINGOS',
  'G.S 128 ABIRA',
  'G.S 131 JORGE COCK QUEVEDO',
  'G.S 138 ARAWAK',
  'G.S 142 FORJADORES',
  'G.S 145 KINICH AHAU',
  'G.S 157 BUENA AVENTURA',
  'G.S 164 LA CAMPIÑA',
  'G.S 168 EMMANUEL',
  'G.S 171 SALVADORES',
  'G.S 174 CAMELOT',
  'G.S 198 TITANES',
  'G.S 202 SANTA MARIA DE LA CANDELARIA',
  'G.S 210 ORION',
  'G.S 213 UCO',
  'G.S 421 HORIZONTES',
  'G.S 934 FAWKES',
] as const;
